"""Triton lowering generated by NineToothed from ssa.Program.

Kernel: ntops_add
Lowering IR: ssa.Program
"""

import triton
import triton.language as tl
from math import floor
from triton.language.extra import libdevice


@triton.jit
def ntops_add_kernel(
    input,
    other,
    alpha,
    output,
    ninetoothed_ninetoothed_tensor_0_size_0,
    ninetoothed_ninetoothed_tensor_0_size_1,
    ninetoothed_ninetoothed_tensor_0_stride_0,
    ninetoothed_ninetoothed_tensor_0_stride_1,
    ninetoothed_ninetoothed_tensor_1_size_0,
    ninetoothed_ninetoothed_tensor_1_size_1,
    ninetoothed_ninetoothed_tensor_1_stride_0,
    ninetoothed_ninetoothed_tensor_1_stride_1,
    ninetoothed_ninetoothed_tensor_3_size_0,
    ninetoothed_ninetoothed_tensor_3_size_1,
    ninetoothed_ninetoothed_tensor_3_stride_0,
    ninetoothed_ninetoothed_tensor_3_stride_1,
    BLOCK: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    index = offsets
    mask = offsets < ((((ninetoothed_ninetoothed_tensor_3_size_0 * ninetoothed_ninetoothed_tensor_3_size_1 - 127 - 1 + 128 - 1) // 128 + 1)) * (128))
    v0 = (alpha * tl.load(other + (((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_1_size_1 * ninetoothed_ninetoothed_tensor_1_stride_0 + (((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_1_size_1 * ninetoothed_ninetoothed_tensor_1_stride_1, mask=(mask) & (True & (((((index)) // ((128)))) < (ninetoothed_ninetoothed_tensor_1_size_0 * ninetoothed_ninetoothed_tensor_1_size_1 - 127 - 1 + 128 - 1) // 128 + 1) & (((((index)) // ((128)))) >= 0) & (((index % (128))) < 128) & (((index % (128))) >= 0) & (((((index)) // ((128)))) * 128 + ((index % (128))) < ninetoothed_ninetoothed_tensor_1_size_0 * ninetoothed_ninetoothed_tensor_1_size_1) & (((((index)) // ((128)))) * 128 + ((index % (128))) >= 0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_1_size_1 < ninetoothed_ninetoothed_tensor_1_size_0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_1_size_1 >= 0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_1_size_1 < ninetoothed_ninetoothed_tensor_1_size_1) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_1_size_1 >= 0)), other=0.0))
    v1 = (tl.load(input + (((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_0_size_1 * ninetoothed_ninetoothed_tensor_0_stride_0 + (((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_0_size_1 * ninetoothed_ninetoothed_tensor_0_stride_1, mask=(mask) & (True & (((((index)) // ((128)))) < (ninetoothed_ninetoothed_tensor_0_size_0 * ninetoothed_ninetoothed_tensor_0_size_1 - 127 - 1 + 128 - 1) // 128 + 1) & (((((index)) // ((128)))) >= 0) & (((index % (128))) < 128) & (((index % (128))) >= 0) & (((((index)) // ((128)))) * 128 + ((index % (128))) < ninetoothed_ninetoothed_tensor_0_size_0 * ninetoothed_ninetoothed_tensor_0_size_1) & (((((index)) // ((128)))) * 128 + ((index % (128))) >= 0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_0_size_1 < ninetoothed_ninetoothed_tensor_0_size_0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_0_size_1 >= 0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_0_size_1 < ninetoothed_ninetoothed_tensor_0_size_1) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_0_size_1 >= 0)), other=0.0) + v0)
    tl.store(output + (((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_3_size_1 * ninetoothed_ninetoothed_tensor_3_stride_0 + (((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_3_size_1 * ninetoothed_ninetoothed_tensor_3_stride_1, v1, mask=(mask) & (True & (((((index)) // ((128)))) < (ninetoothed_ninetoothed_tensor_3_size_0 * ninetoothed_ninetoothed_tensor_3_size_1 - 127 - 1 + 128 - 1) // 128 + 1) & (((((index)) // ((128)))) >= 0) & (((index % (128))) < 128) & (((index % (128))) >= 0) & (((((index)) // ((128)))) * 128 + ((index % (128))) < ninetoothed_ninetoothed_tensor_3_size_0 * ninetoothed_ninetoothed_tensor_3_size_1) & (((((index)) // ((128)))) * 128 + ((index % (128))) >= 0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_3_size_1 < ninetoothed_ninetoothed_tensor_3_size_0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) // ninetoothed_ninetoothed_tensor_3_size_1 >= 0) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_3_size_1 < ninetoothed_ninetoothed_tensor_3_size_1) & ((((((index)) // ((128)))) * 128 + ((index % (128)))) % ninetoothed_ninetoothed_tensor_3_size_1 >= 0)))

def launch_ntops_add(input, other, alpha, output, ninetoothed_ninetoothed_tensor_0_size_0, ninetoothed_ninetoothed_tensor_0_size_1, ninetoothed_ninetoothed_tensor_0_stride_0, ninetoothed_ninetoothed_tensor_0_stride_1, ninetoothed_ninetoothed_tensor_1_size_0, ninetoothed_ninetoothed_tensor_1_size_1, ninetoothed_ninetoothed_tensor_1_stride_0, ninetoothed_ninetoothed_tensor_1_stride_1, ninetoothed_ninetoothed_tensor_3_size_0, ninetoothed_ninetoothed_tensor_3_size_1, ninetoothed_ninetoothed_tensor_3_stride_0, ninetoothed_ninetoothed_tensor_3_stride_1, _ninetoothed_num_warps=4, _ninetoothed_num_stages=3):
    block = 256
    grid = ((((ninetoothed_ninetoothed_tensor_3_size_0 * ninetoothed_ninetoothed_tensor_3_size_1 - 127 - 1 + 128 - 1) // 128 + 1)) * (128),) if False else (triton.cdiv((((ninetoothed_ninetoothed_tensor_3_size_0 * ninetoothed_ninetoothed_tensor_3_size_1 - 127 - 1 + 128 - 1) // 128 + 1)) * (128), block),)
    ntops_add_kernel[grid](
        input,
        other,
        alpha,
        output,
        ninetoothed_ninetoothed_tensor_0_size_0,
        ninetoothed_ninetoothed_tensor_0_size_1,
        ninetoothed_ninetoothed_tensor_0_stride_0,
        ninetoothed_ninetoothed_tensor_0_stride_1,
        ninetoothed_ninetoothed_tensor_1_size_0,
        ninetoothed_ninetoothed_tensor_1_size_1,
        ninetoothed_ninetoothed_tensor_1_stride_0,
        ninetoothed_ninetoothed_tensor_1_stride_1,
        ninetoothed_ninetoothed_tensor_3_size_0,
        ninetoothed_ninetoothed_tensor_3_size_1,
        ninetoothed_ninetoothed_tensor_3_stride_0,
        ninetoothed_ninetoothed_tensor_3_stride_1,
        BLOCK=block,
        num_warps=_ninetoothed_num_warps,
        num_stages=_ninetoothed_num_stages,
    )
    return output
